version: "3"
services:
  db:
    image: postgis/postgis:13-3.0-alpine
    environment:
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: vaccinespotter_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "15432:5432"

  bootstrap_db:
    build: .
    image: covid-vaccine-spotter:1
    command: "echo 'Bootstrap complete!'"
    depends_on:
      - db
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=dev_password
      - DB_NAME=vaccinespotter_development
      - LOG_LEVEL=notice
      - NODE_ENV=development
    entrypoint: /app/bin/docker/bootstrap-entrypoint

  task_runner:
    image: covid-vaccine-spotter:1
    command: "bin/refresh-website"
    depends_on:
      - bootstrap_db
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=dev_password
      - DB_NAME=vaccinespotter_development
      - LOG_LEVEL=debug
      - RUN_ONCE=true
      - NODE_ENV=development
    entrypoint: /app/bin/docker/entrypoint

volumes:
  node_modules:
  postgres_data:
