apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Chart.Name }}-db-backup-public-cronjob
  labels:
    app: {{ .Chart.Name }}-db-backup-public
spec:
  schedule: "22 0 * * *"
  concurrencyPolicy: Forbid
  suspend: false
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: {{ .Chart.Name }}-db-backup-public
          annotations:
            checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        spec:
          restartPolicy: Never
          imagePullSecrets:
            - name: {{ .Chart.Name }}-container-registry-secret
          containers:
            - name: {{ .Chart.Name }}-db-backup-public
              image: {{ index .Values.werf.image "vaccinespotter" }}
              args: ["bin/run", "db:backup:public"]
              env:
                - name: LOG_LEVEL
                  value: info
              envFrom:
                - secretRef:
                    name: {{ .Chart.Name }}-secrets
